# NOTEBOOK SETTINGS
[notebook]
dir = "~/note-taking-system"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 4

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "ginn"


# GROUP OVERRIDES

# Task group
[group.task]
paths = ["task/*"]

[group.task.note]
filename = "{{format-date now '%d-%m-%Y'}}-task-yrism"
template = "task-yrism.md"


[group.cornell]
paths = ["cornell/*"]

[group.cornell.note]
filename = "{{format-date now 'timestamp'}}.{{slug title}}"
template = "cornell.md"

[group.idea]
paths = ["idea/*"]

[group.idea.note]
paths = ["idea"]
filename = "{{format-date now 'timestamp'}}-{{slug title}}"
template = "idea.md"


# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true
link-format = "[[{{metadata.id}}|{{slug title}}]]"

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "fish"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"
fzf-option = "--height 40% --border"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"
idea = "--sort created idea"
task = "--sort created task"
cornell = "--sort created cornell"

# COMMAND ALIASES
[alias]

# Config
c  = 'nvim ~/.config/zk/config.toml'
ct = 'nvim ~/.config/zk/templates/'

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $argv"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Tasks
nt = "zk new --no-input $ZK_NOTEBOOK_DIR/task --group task"
ni = "zk new --title $argv $ZK_NOTEBOOK_DIR/idea --group idea"
nn = "zk new --title $argv $ZK_NOTEBOOK_DIR/cornell --group cornell"

# Listing
t = "zk list --tag $argv"
ls = "zk edit $argv --interactive"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
