#!/bin/bash

options=(
  style=round
  width=6.0
  hidpi=off
  background_color=0xcf1d3b53
  active_color="gradient(top_left=0xff22C7A8,bottom_right=0xff433bff)"
  inactive_color=0xff414550
)

borders "${options[@]}"
